// @index(['./**/*.ts'], f => `export * from '${f.path}';`)
export * from './app/activity.module';
export * from './app/bridge.module';
export * from './app/item.module';
export * from './app/land.module';
export * from './app/room.module';
export * from './app/sleep.module';
export * from './app/tree.module';
export * from './common/app.module';
export * from './common/auth.module';
export * from './common/file.module';
export * from './common/global.module';
export * from './common/user.module';
export * from './common/util.module';
export * from './shop/cart.module';
export * from './shop/order.module';
export * from './shop/product.module';
export * from './shop/review.module';
export * from './shop/wishlist.module';
